services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"   # SQL*Net
      - "5500:5500"   # EM Express
    environment:
      ORACLE_PASSWORD: "hmm1234!@#"
      ORACLE_DATABASE: "XEPDB1"
      APP_USER: "admin"
      APP_USER_PASSWORD: "admin1234"
    volumes:
      - oracle-data:/opt/oracle/oradata
      # - ./db/init:/container-entrypoint-initdb.d

    healthcheck:
      # 헬스체크는 EZCONNECT(//host:port/service) 형식을 쓰면 TNS 없이도 동작합니다.
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/$${ORACLE_PASSWORD}@//localhost:1521/$${ORACLE_DATABASE} || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 30

volumes:
  oracle-data: