services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-free
    ports:
      - "1527:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: "hmm1234**"
      ORACLE_CHARACTERSET: "AL32UTF8"
      TZ: "Asia/Seoul"
    volumes:
      - oracle23-data:/opt/oracle/oradata
      - ./db/init:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/$${ORACLE_PASSWORD}@//127.0.0.1:1521/FREEPDB1 | grep -q '1'"]
      interval: 15s
      timeout: 5s
      retries: 40
volumes:
  oracle23-data: