# =================================================
# DEVELOPMENT PROFILE OVERRIDES
# =================================================
server:
  port: 8080

spring:
  r2dbc:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
logging:
  level:
    com.hmm.backend: DEBUG
# --- API Docs ---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
