# application-local.yml

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1527/FREEPDB1
    username: CBUI_WAS
    password: app1234
    driver-class-name: oracle.jdbc.OracleDriver

swagger:
  enabled: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG